/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const ContactSubmission = IDL.Record({
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const CompanyStats = IDL.Record({
  'employees' : IDL.Nat,
  'projects' : IDL.Nat,
  'offices' : IDL.Nat,
  'years' : IDL.Nat,
});
export const Project = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
});
export const Service = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'iconName' : IDL.Text,
});
export const TeamMember = IDL.Record({
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'role' : IDL.Text,
});
export const Testimonial = IDL.Record({
  'role' : IDL.Text,
  'quote' : IDL.Text,
  'author' : IDL.Text,
  'company' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllContactFormSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getCompanyStats' : IDL.Func([], [CompanyStats], ['query']),
  'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
  'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const ContactSubmission = IDL.Record({
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const CompanyStats = IDL.Record({
    'employees' : IDL.Nat,
    'projects' : IDL.Nat,
    'offices' : IDL.Nat,
    'years' : IDL.Nat,
  });
  const Project = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
  });
  const Service = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'iconName' : IDL.Text,
  });
  const TeamMember = IDL.Record({
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'role' : IDL.Text,
  });
  const Testimonial = IDL.Record({
    'role' : IDL.Text,
    'quote' : IDL.Text,
    'author' : IDL.Text,
    'company' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllContactFormSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getCompanyStats' : IDL.Func([], [CompanyStats], ['query']),
    'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
    'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };